### ISSUE TITLE
Update development setup (when running only call service locally)

### ISSUE THREAD

**Issue by tirithen** [zetkin/call.zetk.in#229]
There where several smaller issues with running the call service:

* ZETKIN_APP_ID and ZETKIN_APP_KEY values are no longer valid (fixed by updating values in ./bin/run_dev)
* It's trying to reach online development services with https that needs to be reached with http (fixed by adding `--env ZETKIN_USE_TLS=0 \` in ./bin/run_dev)
* Missing protocol for main.js redirect (fixed by adding protocol: 'http' around line 60 in server/app.js)

**Comment by tirithen** [comment]
Suggested fixes in https://github.com/zetkin/call.zetk.in/pull/231

**Comment by richardolsson** [comment]
Fixed by #231
