### ISSUE TITLE
Header with branding, user menu et c

### ISSUE THREAD

**Issue by richardolsson** [zetkin/call.zetk.in#29]
Currently, there is no Zetkin branding in Zetkin Call and no way to log out (or go back to dashboard which is where most callers will have come from). Consider a solution for this, perhaps a very small header bar, a hamburger menu, a drawer or a sidebar?

**Comment by richardolsson** [comment]
Having discussed this, a "quit" button (as described in #28) is enough as long as the assignment list page contains links to "my page", log out et c.

**Comment by jensborje** [comment]
High def mockups on suggested solutions for header:

![skarmavbild 2016-12-19 kl 18 29 02](https://cloud.githubusercontent.com/assets/1271517/21322392/20d32d58-c619-11e6-8751-f9e16504284a.png)

![skarmavbild 2016-12-19 kl 18 29 16](https://cloud.githubusercontent.com/assets/1271517/21322397/230dbafc-c619-11e6-9864-14cab243d000.png)

**Comment by richardolsson** [comment]
I like that a lot, especially the second option. Lets put "Zetkin Call" instead of "Ringverktyg" though.
