### ISSUE TITLE
Crash when event activity or location is null

### ISSUE THREAD

**Issue by richardolsson** [zetkin/call.zetk.in#296]
Since a while back, it's possible to create events (actions) that have no physical location (`location == null`) or are uncategorized (`activity == null`). This causes an exception that prevents rendering in the step where the campaigns show up.

**Comment by niklasva82** [comment]
This appears to already be solved. The issue with campaigns not showing up was when campaign for an event is null and is solved by #299 
![image](https://github.com/zetkin/call.zetk.in/assets/14962107/271913d9-fd9b-40ce-b4fa-ea62f06991df)
