### ISSUE TITLE
LaneSwitch tooltip misinterpreted

### ISSUE THREAD

**Issue by richardolsson** [zetkin/call.zetk.in#77]
Test subjects generally notice the `LaneSwitch` tooltip at some point before needing the feature, but not always. Some subjects close it after reading it, while others don't seem to notice it at all, leaving it open throughout the session.

To those who do notice it, the text does not seem to properly explain the feature, and the phrasing (Swedish) makes it a bit difficult to read. Still, after some reasoning and trial and error, people who read the tooltip understand it.

_This was observed (noted as signal 17) during the december 2016 user tests._

**Comment by richardolsson** [comment]
Suggested solutions:

* Come up with new, clever header for the tooltip.
* Make the tooltip modal in some way, maybe as part of a general tutorial framework that can focus on and explain various key interface elements.
* Make it clearer in `LaneOverview` (once opened) that it's all about starting new calls off previous ones, rather than inspecting old calls. For example, maybe replace the list of calls with a list of called targets instead.

**Comment by richardolsson** [comment]
Perhaps add a mouse-over label to the LaneSwitch button.

**Comment by richardolsson** [comment]
An alternative solution is just making the tooltip more prominent, e.g. by inverting it or using blue background.

**Comment by jensborje** [comment]
![skarmavbild 2016-12-13 kl 15 25 46](https://cloud.githubusercontent.com/assets/1271517/21143824/771af612-c148-11e6-94ef-5fc8899ba58d.png)

Suggestions:

- Tooltip with secondary brand color background & white text
- Use buttons with background visible on hover
- Delay appear to after a few seconds
- Fade out / change opacity to other content on page
